import Head from 'next/head'
import Category from '../components/Category'

export default function Home() {
  return (
    <>
      <Head>
        <title>nemo.kz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     <Category/>
     
    </>
  )
}
